export const ADD_SIGNUP_BEGIN = 'ADD_SIGNUP_BEGIN';
export const ADD_SIGNUP_SUCCESS = 'ADD_SIGNUP_SUCCESS';
export const ADD_SIGNUP_FAILURE = 'ADD_SIGNUP_FAILURE';

export const ADD_SIGNUP_BEGIN_BUYFORM = 'ADD_SIGNUP_BEGIN_BUYFORM';
export const ADD_SIGNUP_SUCCESS_BUYFORM = 'ADD_SIGNUP_SUCCESS_BUYFORM';
export const ADD_SIGNUP_FAILURE_BUYFORM = 'ADD_SIGNUP_FAILURE_BUYFORM';

export const ADD_LOGIN_BEGIN = 'ADD_LOGIN_BEGIN';
export const ADD_LOGIN_SUCCESS = 'ADD_LOGIN_SUCCESS';
export const ADD_LOGIN_FAILURE = 'ADD_LOGIN_FAILURE';